import paramiko
c = paramiko.SSHClient()
c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
c.connect('103.166.183.57', port=24700, username='root', password='*U>yC8swHFoI<LvAiOR3', timeout=10)
_, out, err = c.exec_command('curl -s http://localhost:3001/orders | head -c 500')
print("ORDERS:", out.read().decode())
print("ERR:", err.read().decode())
_, out2, _ = c.exec_command('pm2 logs tuan-food-api --lines 20 --nostream')
print("PM2 LOGS:", out2.read().decode())
c.close()
